services:
  client:
    image: react-template/client
    container_name: client
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/client:/app/packages/client
      - ./packages/shared:/app/packages/shared
      - ./node_modules:/app/node_modules
  server:
    image: react-template/server
    container_name: server
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./packages/server:/app/packages/server
      - ./packages/shared:/app/packages/shared
      - ./node_modules:/app/node_modules
